### ISSUE TITLE
identity_file not passed to ssh command

### ISSUE THREAD

**Issue by fpkoschitzki** [cornyhorse/sshaman#7]

**Comment by fpkoschitzki** [comment]
If the field identity_file is not empty, it should be passed to ssh with -i <identity_file>.

**Comment by cornyhorse** [comment]
Yes!  Thanks for filing this I meant to include that in a list of issues I made before releasing.  I'm going to try to make sure all the flags work this weekend!

**Comment by cornyhorse** [comment]
Hi @fpkoschitzki , this was actually easier than I thought. I've gone ahead and released https://github.com/cornyhorse/sshaman/releases/tag/0.1.1 which addresses the identity file not being passed. Please let me know if have any issues with it. I don't have unit tests for it, but I tested it locally and it works as I expect it!
